# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: c murray
email: cmurray7@u.northwestern.edu
description: > # this means to ignore newlines until "baseurl:"
  computational neuroscience student + statistical programmer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cmurray7.github.io" # the base hostname & protocol for your site
twitter_username: cmurray_7
github_username:  cmurray7

# Build settings
markdown: kramdown

#media things
path_to_media: '/assets/'
headshot: 'cary.jpg'
