# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HELLO!
email:  " carolyn.elizabeth.murray@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  cary murray - a computational scientist intrigued by sensation and perception at a neural level
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cmurray7.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: " cmurray7"
linkedIn_link: "in/carolyn-murray-8825b390"
linkedIn_name:  " Carolyn Murray"

# Build settings
markdown: kramdown
